# CMake generated Testfile for 
# Source directory: /Users/huanghong/Downloads/re2-main
# Build directory: /Users/huanghong/Downloads/re2-main/hh
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(charclass_test "/Users/huanghong/Downloads/re2-main/hh/charclass_test")
set_tests_properties(charclass_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/huanghong/Downloads/re2-main/CMakeLists.txt;158;add_test;/Users/huanghong/Downloads/re2-main/CMakeLists.txt;0;")
add_test(compile_test "/Users/huanghong/Downloads/re2-main/hh/compile_test")
set_tests_properties(compile_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/huanghong/Downloads/re2-main/CMakeLists.txt;158;add_test;/Users/huanghong/Downloads/re2-main/CMakeLists.txt;0;")
add_test(filtered_re2_test "/Users/huanghong/Downloads/re2-main/hh/filtered_re2_test")
set_tests_properties(filtered_re2_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/huanghong/Downloads/re2-main/CMakeLists.txt;158;add_test;/Users/huanghong/Downloads/re2-main/CMakeLists.txt;0;")
add_test(mimics_pcre_test "/Users/huanghong/Downloads/re2-main/hh/mimics_pcre_test")
set_tests_properties(mimics_pcre_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/huanghong/Downloads/re2-main/CMakeLists.txt;158;add_test;/Users/huanghong/Downloads/re2-main/CMakeLists.txt;0;")
add_test(parse_test "/Users/huanghong/Downloads/re2-main/hh/parse_test")
set_tests_properties(parse_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/huanghong/Downloads/re2-main/CMakeLists.txt;158;add_test;/Users/huanghong/Downloads/re2-main/CMakeLists.txt;0;")
add_test(possible_match_test "/Users/huanghong/Downloads/re2-main/hh/possible_match_test")
set_tests_properties(possible_match_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/huanghong/Downloads/re2-main/CMakeLists.txt;158;add_test;/Users/huanghong/Downloads/re2-main/CMakeLists.txt;0;")
add_test(re2_test "/Users/huanghong/Downloads/re2-main/hh/re2_test")
set_tests_properties(re2_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/huanghong/Downloads/re2-main/CMakeLists.txt;158;add_test;/Users/huanghong/Downloads/re2-main/CMakeLists.txt;0;")
add_test(re2_arg_test "/Users/huanghong/Downloads/re2-main/hh/re2_arg_test")
set_tests_properties(re2_arg_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/huanghong/Downloads/re2-main/CMakeLists.txt;158;add_test;/Users/huanghong/Downloads/re2-main/CMakeLists.txt;0;")
add_test(regexp_test "/Users/huanghong/Downloads/re2-main/hh/regexp_test")
set_tests_properties(regexp_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/huanghong/Downloads/re2-main/CMakeLists.txt;158;add_test;/Users/huanghong/Downloads/re2-main/CMakeLists.txt;0;")
add_test(required_prefix_test "/Users/huanghong/Downloads/re2-main/hh/required_prefix_test")
set_tests_properties(required_prefix_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/huanghong/Downloads/re2-main/CMakeLists.txt;158;add_test;/Users/huanghong/Downloads/re2-main/CMakeLists.txt;0;")
add_test(search_test "/Users/huanghong/Downloads/re2-main/hh/search_test")
set_tests_properties(search_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/huanghong/Downloads/re2-main/CMakeLists.txt;158;add_test;/Users/huanghong/Downloads/re2-main/CMakeLists.txt;0;")
add_test(set_test "/Users/huanghong/Downloads/re2-main/hh/set_test")
set_tests_properties(set_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/huanghong/Downloads/re2-main/CMakeLists.txt;158;add_test;/Users/huanghong/Downloads/re2-main/CMakeLists.txt;0;")
add_test(simplify_test "/Users/huanghong/Downloads/re2-main/hh/simplify_test")
set_tests_properties(simplify_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/huanghong/Downloads/re2-main/CMakeLists.txt;158;add_test;/Users/huanghong/Downloads/re2-main/CMakeLists.txt;0;")
add_test(string_generator_test "/Users/huanghong/Downloads/re2-main/hh/string_generator_test")
set_tests_properties(string_generator_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/huanghong/Downloads/re2-main/CMakeLists.txt;158;add_test;/Users/huanghong/Downloads/re2-main/CMakeLists.txt;0;")
add_test(dfa_test "/Users/huanghong/Downloads/re2-main/hh/dfa_test")
set_tests_properties(dfa_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/huanghong/Downloads/re2-main/CMakeLists.txt;158;add_test;/Users/huanghong/Downloads/re2-main/CMakeLists.txt;0;")
add_test(exhaustive1_test "/Users/huanghong/Downloads/re2-main/hh/exhaustive1_test")
set_tests_properties(exhaustive1_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/huanghong/Downloads/re2-main/CMakeLists.txt;158;add_test;/Users/huanghong/Downloads/re2-main/CMakeLists.txt;0;")
add_test(exhaustive2_test "/Users/huanghong/Downloads/re2-main/hh/exhaustive2_test")
set_tests_properties(exhaustive2_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/huanghong/Downloads/re2-main/CMakeLists.txt;158;add_test;/Users/huanghong/Downloads/re2-main/CMakeLists.txt;0;")
add_test(exhaustive3_test "/Users/huanghong/Downloads/re2-main/hh/exhaustive3_test")
set_tests_properties(exhaustive3_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/huanghong/Downloads/re2-main/CMakeLists.txt;158;add_test;/Users/huanghong/Downloads/re2-main/CMakeLists.txt;0;")
add_test(exhaustive_test "/Users/huanghong/Downloads/re2-main/hh/exhaustive_test")
set_tests_properties(exhaustive_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/huanghong/Downloads/re2-main/CMakeLists.txt;158;add_test;/Users/huanghong/Downloads/re2-main/CMakeLists.txt;0;")
add_test(random_test "/Users/huanghong/Downloads/re2-main/hh/random_test")
set_tests_properties(random_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/huanghong/Downloads/re2-main/CMakeLists.txt;158;add_test;/Users/huanghong/Downloads/re2-main/CMakeLists.txt;0;")
